[package]
name = "ievr_dataminer"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam = "0.8.4"
ievr_cfg_bin_editor_core = { path = "../ievr_cfg_bin_editor/ievr_cfg_bin_editor-core" }
memmap2 = "0.9"
regex = "1.12.2"
rusqlite = "0.38.0"
